### PR TITLE
Support rack2.0

### PR DESCRIPTION
**Pull request by nog**
I want to use turnout on Rails 5.0
I think it's okay beacause pass the test.
Pointed it me and if there is a problem. I will fix it.

### CODE REVIEW

**Comment by adamcrown** [comment]
Thanks. This looks good. It's been hard to find any simple documentation on what actually changed in Rack 2.0. Maybe I just need to look through the code. I don't imagine it would change much for this gem though.

I'll push out a new gem version soon.

**Comment by blunckr** [comment]
Any idea when that version will be out?

**Comment by bogdanRada** [comment]
This won't work though , because RUBY_VERSION is evaluated when building the gem, and not at runtime.  

So would be better to keep in gemspec this line
```
 s.add_dependency('rack', '>= 1.3', '< 3')
```

and add in your own application Gemfile the version of rack you need to use .

**Comment by bogdanRada** [comment]
@adamcrown , have you checked my comment?  Please revert this pull request.

**Comment by nog** [comment]
Oh... sorry! Please revert this PR @adamcrown

**Comment by adamcrown** [comment]
I think you're right. Best to just keep it simple with `s.add_dependency('rack', '>= 1.3', '< 3')`. I'll make the change now.

**Comment by bogdanRada** [comment]
Thank you very much :)

**Pull request merged**
